swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Card Financial Settlement'
 description: 'Description'
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-card-financial-settlement/1.0.0
schemes:
 - https
paths:
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/updation:
    put:
      tags:
      - update
      operationId: updateCardFinancialSettlementProcedure
      summary: Update details of an active card financial settlement transaction
      description: Update  Update/amend details of an active card financial settlement process,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Settlement Request Payload
        schema:
          $ref: '#/definitions/CardFinancialSettlementSettlementBase'
      responses:
        200:
          description: Successful Update details of an active card financial settlement transaction
          schema:
            $ref: '#/definitions/CardFinancialSettlementSettlementBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/recording:
    post:
      tags:
      - record
      operationId: recordCardFinancialSettlementProcedure
      summary: Record activity/details related to an active financial settlement transaction
      description: Record  Record activity/feedback related to card financial settlement,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Record Request Payload
        schema:
          $ref: '#/definitions/CardFinancialSettlementRecordBase'
      responses:
        201:
          description: Successful Record activity/details related to an active financial settlement transaction
          schema:
            $ref: '#/definitions/CardFinancialSettlementRecordBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCardFinancialSettlementProcedureUpdate
      summary: Request the processing for card financial settlement
      description: Request  Request card financial settlement processing,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Settlement Request Payload
        schema:
          $ref: '#/definitions/CardFinancialSettlementSettlementBase'
      responses:
        200:
          description: Successful Request the processing for card financial settlement
          schema:
            $ref: '#/definitions/CardFinancialSettlementSettlementBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/requisition:
    post:
      tags:
      - request
      operationId: requestCardFinancialSettlementProcedureCreate
      summary: Request the processing for card financial settlement
      description: Request  Request card financial settlement processing,
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: Settlement Request Payload
        schema:
          $ref: '#/definitions/CardFinancialSettlementSettlementBase'
      responses:
        201:
          description: Successful Request the processing for card financial settlement
          schema:
            $ref: '#/definitions/CardFinancialSettlementSettlementBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardFinancialSettlementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- 
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
              example: ['ID726464', 'ID7264642']
  /card-financial-settlement/card-financial-settlement-procedure/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardFinancialSettlementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Consolidation',  'Processing',  'Instruction',  'Payment',  'Reporting', ]
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardFinancialSettlementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 'BQ1'
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
              example: ['BQID1', 'BQID2']
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardFinancialSettlement
      summary: Retrieve a Card Financial Settlement Record
      description: Retrieve a Card Financial Settlement Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Financial Settlement Report
          schema:
            $ref: '#/definitions/CardFinancialSettlementSettlementBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/consolidation/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardFinancialSettlementConsolidation
      summary: Retrieve a Card Financial Settlement Consolidation Record
      description: Retrieve a Card Financial Settlement Consolidation Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Consolidation BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Financial Settlement Consolidation Report
          schema:
            $ref: '#/definitions/CardFinancialSettlementConsolidationBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/processing/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardFinancialSettlementProcessing
      summary: Retrieve a Card Financial Settlement Processing Record
      description: Retrieve a Card Financial Settlement Processing Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Processing BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Financial Settlement Processing Report
          schema:
            $ref: '#/definitions/CardFinancialSettlementProcessingBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/instruction/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardFinancialSettlementInstruction
      summary: Retrieve a Card Financial Settlement Instruction Record
      description: Retrieve a Card Financial Settlement Instruction Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Instruction BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Financial Settlement Instruction Report
          schema:
            $ref: '#/definitions/CardFinancialSettlementInstructionBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/payment/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardFinancialSettlementPayment
      summary: Retrieve a Card Financial Settlement Payment Record
      description: Retrieve a Card Financial Settlement Payment Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Payment BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Financial Settlement Payment Report
          schema:
            $ref: '#/definitions/CardFinancialSettlementPaymentBaseWithIdAndRoot'
  /card-financial-settlement/card-financial-settlement-procedure/{cr-reference-id}/reporting/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardFinancialSettlementReporting
      summary: Retrieve a Card Financial Settlement Reporting Record
      description: Retrieve a Card Financial Settlement Reporting Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Financial Settlement Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Reporting BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Financial Settlement Reporting Report
          schema:
            $ref: '#/definitions/CardFinancialSettlementReportingBaseWithIdAndRoot'
