swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Card Clearing'
 description: 'Description'
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-card-clearing/1.0.0
schemes:
 - https
paths:
  /card-clearing/card-clearing-procedure/{cr-reference-id}/updation:
    put:
      tags:
      - update
      operationId: updateCardClearingProcedure
      summary: Update/amend details of a pending card clearing transaction
      description: Update  Update pending card clearing transaction,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Clearing Request Payload
        schema:
          $ref: '#/definitions/CardClearingClearingBase'
      responses:
        200:
          description: Successful Update/amend details of a pending card clearing transaction
          schema:
            $ref: '#/definitions/CardClearingClearingWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/recording:
    post:
      tags:
      - record
      operationId: recordCardClearingProcedure
      summary: Record activity/feedback relating to card clearing processing
      description: Record  Record activity/feedback relating to card clearing activity,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Record Request Payload
        schema:
          $ref: '#/definitions/CardClearingRecordBase'
      responses:
        201:
          description: Successful Record activity/feedback relating to card clearing processing
          schema:
            $ref: '#/definitions/CardClearingRecordWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/capture/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeCardClearingProcedureCaptureUpdate
      summary: Execute card clearing transaction
      description: Execute  Execute card clearing transaction,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Capture BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Capture request payload
        schema:
          $ref: '#/definitions/CardClearingCaptureBase'
      responses:
        200:
          description: Successful Execute card clearing transaction
          schema:
            $ref: '#/definitions/CardClearingCaptureWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/capture/execution:
    post:
      tags:
      - execute
      operationId: executeCardClearingProcedureCaptureCreate
      summary: Execute card clearing transaction
      description: Execute  Execute card clearing transaction,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Capture Request Payload
        schema:
          $ref: '#/definitions/CardClearingCaptureBase'
      responses:
        201:
          description: Successful Execute card clearing transaction
          schema:
            $ref: '#/definitions/CardClearingCaptureWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/capture/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCardClearingProcedureCaptureUpdate
      summary: Request card clearing batch processing
      description: Request  Card clearing batch upload and distribution'
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Capture BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Capture request payload
        schema:
          $ref: '#/definitions/CardClearingCaptureBase'
      responses:
        200:
          description: Successful Request card clearing batch processing
          schema:
            $ref: '#/definitions/CardClearingCaptureWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/capture/requisition:
    post:
      tags:
      - request
      operationId: requestCardClearingProcedureCaptureCreate
      summary: Request card clearing batch processing
      description: Request  Card clearing batch upload and distribution'
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Capture Request Payload
        schema:
          $ref: '#/definitions/CardClearingCaptureBase'
      responses:
        201:
          description: Successful Request card clearing batch processing
          schema:
            $ref: '#/definitions/CardClearingCaptureWithIdAndRoot'
  /card-clearing/card-clearing-procedure:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardClearingReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- 
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /card-clearing/card-clearing-procedure/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardClearingBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Capture',  'Addressing',  'FXConversion',  'Fees',  'Matching',  'Reconciliation',  'Routing',  'Reporting', ]
  /card-clearing/card-clearing-procedure/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardClearingBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 'BQ1'
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['BQID1', 'BQID2']
  /card-clearing/card-clearing-procedure/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearing
      summary: Retrieve a Card Clearing Record
      description: Retrieve a Card Clearing Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Report
          schema:
            $ref: '#/definitions/CardClearingClearingWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/capture/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingCapture
      summary: Retrieve a Card Clearing Capture Record
      description: Retrieve a Card Clearing Capture Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Capture BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Capture Report
          schema:
            $ref: '#/definitions/CardClearingCaptureWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/addressing/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingAddressing
      summary: Retrieve a Card Clearing Addressing Record
      description: Retrieve a Card Clearing Addressing Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Addressing BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Addressing Report
          schema:
            $ref: '#/definitions/CardClearingAddressingWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/fxconversion/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingFXConversion
      summary: Retrieve a Card Clearing FXConversion Record
      description: Retrieve a Card Clearing FXConversion Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: FXConversion BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing FXConversion Report
          schema:
            $ref: '#/definitions/CardClearingFXConversionWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/fees/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingFees
      summary: Retrieve a Card Clearing Fees Record
      description: Retrieve a Card Clearing Fees Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Fees BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Fees Report
          schema:
            $ref: '#/definitions/CardClearingFeesWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/matching/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingMatching
      summary: Retrieve a Card Clearing Matching Record
      description: Retrieve a Card Clearing Matching Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Matching BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Matching Report
          schema:
            $ref: '#/definitions/CardClearingMatchingWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/reconciliation/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingReconciliation
      summary: Retrieve a Card Clearing Reconciliation Record
      description: Retrieve a Card Clearing Reconciliation Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Reconciliation BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Reconciliation Report
          schema:
            $ref: '#/definitions/CardClearingReconciliationWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/routing/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingRouting
      summary: Retrieve a Card Clearing Routing Record
      description: Retrieve a Card Clearing Routing Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Routing BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Routing Report
          schema:
            $ref: '#/definitions/CardClearingRoutingWithIdAndRoot'
  /card-clearing/card-clearing-procedure/{cr-reference-id}/reporting/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardClearingReporting
      summary: Retrieve a Card Clearing Reporting Record
      description: Retrieve a Card Clearing Reporting Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Clearing Process Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Reporting BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Clearing Reporting Report
          schema:
            $ref: '#/definitions/CardClearingReportingWithIdAndRoot'
