swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Card Case'
 description: 'Description'
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-card-case/1.0.0
schemes:
 - https
paths:
  /card-case/card-case-procedure/{cr-reference-id}/updation:
    put:
      tags:
      - update
      operationId: updateCardCaseProcedure
      summary: Update details of an active card case
      description: Update  Update details of an active card case,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Cardcase Request Payload
        schema:
          $ref: '#/definitions/CardCaseCardcaseBase'
      responses:
        200:
          description: Successful Update details of an active card case
          schema:
            $ref: '#/definitions/CardCaseCardcaseWithIdAndRoot'
  /card-case/card-case-procedure/{cr-reference-id}/recording:
    post:
      tags:
      - record
      operationId: recordCardCaseProcedure
      summary: Provide documents/transaction details for an active card case
      description: Record  Provide documents/transactions/feedback against a card case,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Record Request Payload
        schema:
          $ref: '#/definitions/CardCaseRecordBase'
      responses:
        201:
          description: Successful Provide documents/transaction details for an active card case
          schema:
            $ref: '#/definitions/CardCaseRecordWithIdAndRoot'
  /card-case/card-case-procedure/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeCardCaseProcedureUpdate
      summary: Initiate card case processing
      description: Execute  initiate a new card case procedure,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Cardcase Request Payload
        schema:
          $ref: '#/definitions/CardCaseCardcaseBase'
      responses:
        200:
          description: Successful Initiate card case processing
          schema:
            $ref: '#/definitions/CardCaseCardcaseWithIdAndRoot'
  /card-case/card-case-procedure/execution:
    post:
      tags:
      - execute
      operationId: executeCardCaseProcedureCreate
      summary: Initiate card case processing
      description: Execute  initiate a new card case procedure,
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: Cardcase Request Payload
        schema:
          $ref: '#/definitions/CardCaseCardcaseBase'
      responses:
        201:
          description: Successful Initiate card case processing
          schema:
            $ref: '#/definitions/CardCaseCardcaseWithIdAndRoot'
  /card-case/card-case-procedure/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCardCaseProcedureUpdate
      summary: Request intervention/arbitration for an active card case
      description: Request  Request arbitration/decisioning for a card case,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Cardcase Request Payload
        schema:
          $ref: '#/definitions/CardCaseCardcaseBase'
      responses:
        200:
          description: Successful Request intervention/arbitration for an active card case
          schema:
            $ref: '#/definitions/CardCaseCardcaseWithIdAndRoot'
  /card-case/card-case-procedure/requisition:
    post:
      tags:
      - request
      operationId: requestCardCaseProcedureCreate
      summary: Request intervention/arbitration for an active card case
      description: Request  Request arbitration/decisioning for a card case,
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: Cardcase Request Payload
        schema:
          $ref: '#/definitions/CardCaseCardcaseBase'
      responses:
        201:
          description: Successful Request intervention/arbitration for an active card case
          schema:
            $ref: '#/definitions/CardCaseCardcaseWithIdAndRoot'
  /card-case/card-case-procedure:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardCaseReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- 
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /card-case/card-case-procedure/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardCaseBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Consolidation',  'Chargeback',  'Arbitration',  'Resolution', ]
  /card-case/card-case-procedure/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardCaseBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 'BQ1'
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['BQID1', 'BQID2']
  /card-case/card-case-procedure/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardCase
      summary: Retrieve a Card Case Record
      description: Retrieve a Card Case Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Case Report
          schema:
            $ref: '#/definitions/CardCaseCardCaseWithIdAndRoot'
  /card-case/card-case-procedure/{cr-reference-id}/consolidation/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardCaseConsolidation
      summary: Retrieve a Card Case Consolidation Record
      description: Retrieve a Card Case Consolidation Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Consolidation BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Case Consolidation Report
          schema:
            $ref: '#/definitions/CardCaseConsolidationWithIdAndRoot'
  /card-case/card-case-procedure/{cr-reference-id}/chargeback/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardCaseChargeback
      summary: Retrieve a Card Case Chargeback Record
      description: Retrieve a Card Case Chargeback Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Chargeback BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Case Chargeback Report
          schema:
            $ref: '#/definitions/CardCaseChargebackWithIdAndRoot'
  /card-case/card-case-procedure/{cr-reference-id}/arbitration/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardCaseArbitration
      summary: Retrieve a Card Case Arbitration Record
      description: Retrieve a Card Case Arbitration Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Arbitration BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Case Arbitration Report
          schema:
            $ref: '#/definitions/CardCaseArbitrationWithIdAndRoot'
  /card-case/card-case-procedure/{cr-reference-id}/resolution/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardCaseResolution
      summary: Retrieve a Card Case Resolution Record
      description: Retrieve a Card Case Resolution Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Card Case Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Resolution BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card Case Resolution Report
          schema:
            $ref: '#/definitions/CardCaseResolutionWithIdAndRoot'
