swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Card ECommerce Gateway'
 description: 'Description'
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-card-ecommerce-gateway/1.0.0
schemes:
 - https
paths:
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/recording:
    post:
      tags:
      - record
      operationId: recordECommerceGatewayOperatingSession
      summary: Record activity against an eCommerce operating session
      description: Record  Record feedback against the operating session,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Record Request Payload
        schema:
          $ref: '#/definitions/ECommerceGatewayRecordBase'
      responses:
        201:
          description: Successful Record activity against an eCommerce operating session
          schema:
            $ref: '#/definitions/ECommerceGatewayRecordWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/capture/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeECommerceGatewayOperatingSessionCaptureUpdate
      summary: Execute card transaction capture
      description: Execute  Execute card transaction capture,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Capture BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Capture request payload
        schema:
          $ref: '#/definitions/ECommerceGatewayCaptureBase'
      responses:
        200:
          description: Successful Execute card transaction capture
          schema:
            $ref: '#/definitions/ECommerceGatewayCaptureWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/capture/execution:
    post:
      tags:
      - execute
      operationId: executeECommerceGatewayOperatingSessionCaptureCreate
      summary: Execute card transaction capture
      description: Execute  Execute card transaction capture,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Capture Request Payload
        schema:
          $ref: '#/definitions/ECommerceGatewayCaptureBase'
      responses:
        201:
          description: Successful Execute card transaction capture
          schema:
            $ref: '#/definitions/ECommerceGatewayCaptureWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/update/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestECommerceGatewayOperatingSessionUpdateUpdate
      summary: Request reversal processing for a card transaction
      description: Request  Request card transaction reversal,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Update BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Update request payload
        schema:
          $ref: '#/definitions/ECommerceGatewayUpdateBase'
      responses:
        200:
          description: Successful Request reversal processing for a card transaction
          schema:
            $ref: '#/definitions/ECommerceGatewayUpdateWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/update/requisition:
    post:
      tags:
      - request
      operationId: requestECommerceGatewayOperatingSessionUpdateCreate
      summary: Request reversal processing for a card transaction
      description: Request  Request card transaction reversal,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Update Request Payload
        schema:
          $ref: '#/definitions/ECommerceGatewayUpdateBase'
      responses:
        201:
          description: Successful Request reversal processing for a card transaction
          schema:
            $ref: '#/definitions/ECommerceGatewayUpdateWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardECommerceGatewayReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- 
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /e-commerce-gateway/e-commerce-gateway-operating-session/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardECommerceGatewayBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Capture',  'Batch',  'Authentication',  'Authorization',  'Update',  'Reporting', ]
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCardECommerceGatewayBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 'BQ1'
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['BQID1', 'BQID2']
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardECommerceGateway
      summary: Retrieve a Card ECommerce Gateway Record
      description: Retrieve a Card ECommerce Gateway Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card ECommerce Gateway Report
          schema:
            $ref: '#/definitions/ECommerceGatewayOperatingSessionWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/capture/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardECommerceGatewayCapture
      summary: Retrieve a Card ECommerce Gateway Capture Record
      description: Retrieve a Card ECommerce Gateway Capture Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Capture BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card ECommerce Gateway Capture Report
          schema:
            $ref: '#/definitions/ECommerceGatewayCaptureWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/batch/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardECommerceGatewayBatch
      summary: Retrieve a Card ECommerce Gateway Batch Record
      description: Retrieve a Card ECommerce Gateway Batch Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Batch BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card ECommerce Gateway Batch Report
          schema:
            $ref: '#/definitions/ECommerceGatewayBatchWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/authentication/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardECommerceGatewayAuthentication
      summary: Retrieve a Card ECommerce Gateway Authentication Record
      description: Retrieve a Card ECommerce Gateway Authentication Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Authentication BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card ECommerce Gateway Authentication Report
          schema:
            $ref: '#/definitions/ECommerceGatewayAuthenticationWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/authorization/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardECommerceGatewayAuthorization
      summary: Retrieve a Card ECommerce Gateway Authorization Record
      description: Retrieve a Card ECommerce Gateway Authorization Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Authorization BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card ECommerce Gateway Authorization Report
          schema:
            $ref: '#/definitions/ECommerceGatewayAuthorizationWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/update/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardECommerceGatewayUpdate
      summary: Retrieve a Card ECommerce Gateway Update Record
      description: Retrieve a Card ECommerce Gateway Update Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Update BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card ECommerce Gateway Update Report
          schema:
            $ref: '#/definitions/ECommerceGatewayUpdateWithIdAndRoot'
  /e-commerce-gateway/e-commerce-gateway-operating-session/{cr-reference-id}/reporting/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCardECommerceGatewayReporting
      summary: Retrieve a Card ECommerce Gateway Reporting Record
      description: Retrieve a Card ECommerce Gateway Reporting Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: eCommerce Gateway Service Session
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Reporting BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Card ECommerce Gateway Reporting Report
          schema:
            $ref: '#/definitions/ECommerceGatewayReportingWithIdAndRoot'
